version: '3.1'
services:
  db:
    image: postgres:13
    container_name: act15_m7
    environment:
      - POSTGRES_DB=django
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=admin
    ports:
      - "5432:5432"
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: act15
    ports:
      - "80:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: 2023_milena.vardumyan@iticbcn.cat
      PGADMIN_DEFAULT_PASSWORD: milena123
    volumes:
      - pgadmin-data:/var/lib/pgadmin
volumes:
  local_pgdata:
  pgadmin-data:
